import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import './globals.css'
import Providers from './providers'
import classNames from 'classnames'

const nunito = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={classNames('bg-bg min-h-screen flex flex-col', nunito.className)}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
